webconfig {
    app_name = "vcpe-webconfig"
    token_api_enabled = false
    validate_device_id_as_mac_address = true
    filter_output_by_bitmap_enabled = false
    upstream_profiles_enabled = false

    server {
        port = 9000
        localhost_only = false
        metrics_enabled = false
        read_timeout_in_secs = 5
        write_timeout_in_secs = 5
    }

    log {
        level = "info"
        file = ""
        sarama_logger_enabled = false
    }

    jwt {
        enabled = false
        api_token {
	    kids = []
	    capabilities = []
            jwks_enabled = false
        }
	    cpe_token {
	    kids = []
	    }
	    kid {}
        server_api_token_auth {
            enabled = false
        }
        device_api_token_auth {
            enabled = false
        }
    }

    database {
        active_driver = "sqlite"
        sqlite {
            db_file = "/app/data/webconfig.sqlite"
            concurrent_queries = 5
        }
    }

    kafka {
        enabled = false
    }
    kafka_producer {
        enabled = false
    }
    mqtt {
        enabled = false
    }
    webpa {
        enabled = false
    }
    xconf {
        enabled = false
    }
    upstream {
        enabled = false
    }
}