FROM localhost/xb10-dev:latest

ARG TARGET_ARCH=cortexa53
ARG TARGETOS
ARG TARGETARCH

RUN mkdir -p /nvram/secure \
   && mkdir -p /rdklogs/logs

RUN systemctl mask \
   reboot.target \
   rebootCleanUp.service \
   systemd-reboot.service \
   brcm-license.service \
   brcm-cm.service \
   miniupnpd.service \
   rdkssaeccdaemon.service \
   cpcd.service \
   zigbeed-tty.path \
   ble_rcp.service \
   radiusauthd.service \
   rdkssainit.service \
   oem-cm-verification.service \
   rng-tools.service \
   brcm-net.service \
   ProcessResetDetect.service \
   simulator-sysevent.service \
   erouter-rename.service \
   ethwan-static-apply.service \
   ethwan-static-capture.service \
   coredump-upload.service \
   minidump-on-bootup-upload.service

RUN mkdir -p /data_bak /data_bak /nvram/secure/oemdata

RUN ln -s /bin/ifconfig /sbin/ifconfig
#RUN touch /nvram/ETHWAN_ENABLE
ENV SDKTARGETSYSROOT=/
ENV TARGET_ARCH=${TARGET_ARCH}

#RUN echo 'MODEL_NAME=xb10-simulator' >> /etc/device.properties
RUN echo 'MODEL_NAME=SG417DBCT' >> /etc/device.properties

RUN echo 'PS1="[\u@xb10-dev \W]\\$ "' >> /home/root/.bashrc

COPY container/platforms/${TARGETOS}-${TARGETARCH}/runtime-init-xb10 /usr/local/bin/runtime-init-xb10
COPY container/platforms/${TARGETOS}-${TARGETARCH}/vcpe-healthd /usr/local/bin/vcpe-healthd
COPY container/vcpe-healthd.service /etc/systemd/system/vcpe-healthd.service
COPY container/entrypoint.sh /usr/local/bin/xb10-legacy-entrypoint.sh
COPY container/simulator-config.sh /usr/local/bin/simulator-config.sh
COPY container/simulator-config.service /etc/systemd/system/simulator-config.service
COPY container/health-probe.sh /usr/local/bin/xb10-health-probe
COPY container/nvram-sim/ /
COPY container/udhcpc.script.sh /etc/udhcpc.script
RUN chmod 0755 /etc/udhcpc.script

RUN chmod 0755 /usr/local/bin/runtime-init-xb10 /usr/local/bin/vcpe-healthd /usr/local/bin/xb10-legacy-entrypoint.sh /usr/local/bin/xb10-health-probe 
RUN systemctl enable vcpe-healthd.service simulator-config.service

# Fix broken /etc/snmp/snmpd.conf symlink (target /etc/var/ doesn't exist in container)
RUN rm /etc/snmp/snmpd.conf && \
   printf 'agentaddress tcp:127.0.0.1:1161\nsyslocation "RDK Gateway"\nsyscontact admin@localhost\nrocommunity public\nrwcommunity private\ndlmod ccsp_snmp_plugin /usr/lib/libsnmp_plugin.so\n' \
   > /etc/snmp/snmpd.conf

RUN sed -i \
   '/dmcli eRT retv Device.X_CISCO_COM_CableModem.MACAddress/a\        if [ -z "$mac" ]; then mac=`cat /sys/class/net/erouter0/address 2>/dev/null | tr '"'"'[a-f]'"'"' '"'"'[A-F]'"'"'`; fi' \
   /lib/rdk/utils.sh

RUN sed -i 's|https://webpa.rdkcentral.com:8080|http://talaria:6200|g' /etc/partners_defaults.json \
   && sed -i 's|https://webpa-token.com|http://themis:6501|g' /etc/partners_defaults.json \
   && sed -i 's|webpa.rdkcentral.com|webpa|g' /etc/partners_defaults.json \
   && sed -i 's/sleep 300/sleep 5/g' /lib/systemd/system/rfc.service \
   && sed -i 's/sleep 60/sleep 5/g' /lib/systemd/system/ulogd.service \
   && sed -i 's/sleep 30/sleep 5/g' /lib/systemd/system/CcspXdnsSsp.service \
   && sed -i 's/sleep 300/sleep 5/g' /lib/systemd/system/CcspXconf.service \
   && sed -i 's/sleep 30/sleep 5/g' /lib/systemd/system/CcspAdvSecuritySsp.service \
   && sed -i 's/CaptivePortal_Enable=true/CaptivePortal_Enable=false/g' /etc/utopia/system_defaults \
   && sed -i 's/#$GeneralPurposeFirewallRuleCount=1/$GeneralPurposeFirewallRuleCount=1/g' /etc/utopia/system_defaults \
   && sed -i 's/#$GeneralPurposeFirewallRule_1=-A INPUT -i eth0 -j ACCEPT/$GeneralPurposeFirewallRule_1=-I INPUT -i vcpe-health0 -j ACCEPT/g' /etc/utopia/system_defaults


ENTRYPOINT ["/usr/local/bin/runtime-init-xb10"]
CMD ["/usr/local/bin/xb10-legacy-entrypoint.sh", "/sbin/init"]
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 CMD ["/usr/local/bin/vcpe-healthd", "--check"]