#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$repo_root/controlplane"

go test ./internal/app -run '^(TestTriBand24VAPApplyConvergesWithThreeGatewayPHYs|TestTriBandVAPsRemainOutsideManagerOwnership|TestWaitForGatewayVAPsRequiresEveryPlannedSlot|TestVAPFailurePreservesWirelessStateForRetry|TestStatusDisplaysWirelessOwnership|TestMirroredCredentialRotationRecreatesGatewayOnce|TestWirelessApplyDownApplyOrdersPhasesAndRecordsSuccess|TestWirelessApplyRecordsPartialEnsureFailureAndRetainsState|TestReconcileWirelessReleasesChangedAndRemovedRadiosBeforeEnsure|TestReconcileWirelessScaleToZeroReleasesRadioAndGroup|TestDownRetainsWirelessStateWhenReleaseFails|TestStateResetGarbageCollectsAllManagedRadiosBeforeClearingState|TestStateResetPreservesStateWhenManagerCleanupFails|TestGarbageCollectWirelessUsesAllActiveDeployments|TestGarbageCollectWirelessSkipsManagerForIncompleteView|TestCredentialRotationApplyMatrixPreservesRadioIdentity|TestCredentialRotationFailureRetryAndDownRecovery|TestCredentialPersonalModesAndDeploymentIsolation|TestCredentialInvalidValueRejectedBeforeRuntime|TestCredentialSentinelAbsentFromObservableSurfaces|TestCredentialCreatedBeforeRuntimeIsRemovedOnRollback|TestWirelessCredentialFilesAreScopedToServiceConsumers)$'
go test ./internal/hwsim -run '^TestEnsureForContainer(RetriesOneFreshPIDOnMissingNamespace|DoesNotRetryOtherErrors)$'
go test ./internal/secrets -run '^(TestResolveAndValidateWirelessPassphraseProviders|TestValidateWirelessPassphrasesRejectsInvalidValuesWithoutDisclosure)$'

echo 'control-plane wireless fake manager: ok'