FROM docker.io/library/ubuntu:24.04

RUN apt-get update && apt-get upgrade -y && \
   DEBIAN_FRONTEND=noninteractive apt-get -y install ca-certificates

RUN echo "deb [trusted=yes] https://gdcs-dev.github.io/debian stable main" | tee /etc/apt/sources.list.d/custom-packages.list

RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get -y install \
   rbus parodus rbus-elements telemetry utopia webcfg \
   iptables net-tools dnsutils dnsmasq systemd-sysv iputils-ping syslog-ng jq netplan.io \
   libcjson1 libmsgpackc2 curl liblog4c3t64 libjansson4 libspdlog-dev && \
   rm -rf /var/lib/apt/lists/*

COPY --chmod=600 container/50-cloud-init.yaml /etc/netplan/
COPY --chmod=644 container/device.properties /etc/
COPY --chmod=644 container/output.json /opt/
#COPY --chmod=644 container/parodus.service /usr/lib/systemd/system/
#COPY --chmod=755 container/start_parodus.sh /usr/local/bin/
RUN systemctl enable parodus
#COPY --chmod=644 container/parodus2rbus.service /usr/lib/systemd/system/
#RUN systemctl enable parodus2rbus
RUN systemctl enable rbus
# COPY --chmod=644 container/rbus-elements.service /usr/lib/systemd/system/
RUN systemctl enable rbus-elements
#COPY --chmod=644 container/syscfg.service /usr/lib/systemd/system/
#COPY --chmod=755 container/syscfg_init.sh /usr/local/bin/
#RUN systemctl enable syscfg
#COPY --chmod=644 container/telemetry2_0.service /usr/lib/systemd/system/
RUN mkdir -p /nvram
RUN systemctl enable telemetry2_0


COPY container/runtime-init-gateway /usr/local/bin/runtime-init-gateway
COPY container/entrypoint.sh /usr/local/bin/gateway-entrypoint.sh
COPY container/healthcheck.sh /usr/local/bin/healthcheck.sh
RUN chmod +x /usr/local/bin/runtime-init-gateway /usr/local/bin/gateway-entrypoint.sh /usr/local/bin/healthcheck.sh
RUN systemctl disable dnsmasq
RUN systemctl mask systemd-networkd-wait-online

ENTRYPOINT ["/usr/local/bin/runtime-init-gateway"]
CMD ["/usr/local/bin/gateway-entrypoint.sh"]
HEALTHCHECK --interval=30s --timeout=10s --start-period=20s --retries=3 CMD ["/usr/local/bin/healthcheck.sh"]

LABEL org.opencontainers.image.source=https://github.com/gdcs-dev/vcpe
LABEL org.opencontainers.image.description="Gateway Container from the vCPE project"