services:
  routerd:
    image: ${ROUTERD_IMAGE_NAME:-ghcr.io/gdcs-dev/routerd:dev}
    container_name: routerd-${CUSTOMER_ID}
    hostname: routerd-${CUSTOMER_ID}
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      CUSTOMER_ID: ${CUSTOMER_ID}
      LAN1_MAC: ${LAN1_MAC}
      LAN2_MAC: ${LAN2_MAC}
      LAN3_MAC: ${LAN3_MAC}
      LAN4_MAC: ${LAN4_MAC}
      WAN0_MAC: ${WAN0_MAC}
      EROUTER0_MAC: ${EROUTER0_MAC}
      BRLAN0_IPV4: ${BRLAN0_IPV4}
      BRLAN0_IPV6: ${BRLAN0_IPV6}
      WAN0_IPV4: ${WAN0_IPV4}
      WAN0_IPV6: ${WAN0_IPV6}
      EROUTER0_VLAN: ${EROUTER0_VLAN}
      EROUTER0_IPV4: ${EROUTER0_IPV4}
      EROUTER0_IPV4_GATEWAY: ${EROUTER0_IPV4_GATEWAY}
      EROUTER0_IPV6: ${EROUTER0_IPV6}
      EROUTER0_IPV6_GATEWAY: ${EROUTER0_IPV6_GATEWAY}
      ROUTERD_BIN_DIR: ${ROUTERD_BIN_DIR:-/workspace/target/release}
    volumes:
      - ${ROUTERD_SOURCE_ROOT}:/workspace:ro
    networks:
      lan-p1:
        mac_address: ${LAN1_MAC}
      lan-p2:
        mac_address: ${LAN2_MAC}
      lan-p3:
        mac_address: ${LAN3_MAC}
      lan-p4:
        mac_address: ${LAN4_MAC}
      cm:
        mac_address: ${WAN0_MAC}
      wan:
        mac_address: ${EROUTER0_MAC}

networks:
  lan-p1:
    external: true
    name: ${LAN1_NETWORK}
  lan-p2:
    external: true
    name: ${LAN2_NETWORK}
  lan-p3:
    external: true
    name: ${LAN3_NETWORK}
  lan-p4:
    external: true
    name: ${LAN4_NETWORK}
  cm:
    external: true
    name: ${CM_NETWORK}
  wan:
    external: true
    name: ${WAN_NETWORK}
