interface eth1.1081
{
    AdvSendAdvert on;
    AdvManagedFlag on;
    AdvOtherConfigFlag on;
    AdvDefaultLifetime 7200;
    MinRtrAdvInterval 120;
    MaxRtrAdvInterval 180;
};

interface eth1.881
{
    AdvSendAdvert on;
    AdvManagedFlag on;
    AdvOtherConfigFlag on;
    AdvDefaultLifetime 7200;
    MinRtrAdvInterval 120;
    MaxRtrAdvInterval 180;
};

interface eth1.981
{
    AdvSendAdvert on;
    AdvManagedFlag on;
    AdvOtherConfigFlag on;
    AdvDefaultLifetime 7200;
    MinRtrAdvInterval 120;
    MaxRtrAdvInterval 180;
};
