interface eth1.100
{
    AdvSendAdvert on;
    AdvManagedFlag on;
    AdvOtherConfigFlag off;
    AdvDefaultLifetime 240;
    MinDelayBetweenRAs 3;
    MinRtrAdvInterval 120;
    MaxRtrAdvInterval 180;
};
