#include "events.h"

/*
 * events.c - 12-entry AppArmor event fixture table.
 *
 * Covers three gateway-resident processes (dnsmasq, parodus, rbus_elements,
 * telemetry2_0) across three dispositions (DENIED, AUDIT, ALLOWED).
 * PIDs are computed at runtime as (getpid() + index) % 65535.
 */

const AppArmorEvent apparmor_events[FIXTURE_COUNT] = {
    /* 0 */ {
        .profile        = "/usr/sbin/dnsmasq",
        .operation      = "open",
        .name           = "/etc/shadow",
        .comm           = "dnsmasq",
        .apparmor       = "DENIED",
        .severity       = "denied",
        .requested_mask = "r",
        .denied_mask    = "r",
        .fsuid          = 33,
        .ouid           = 0,
    },
    /* 1 */ {
        .profile        = "/usr/sbin/dnsmasq",
        .operation      = "open",
        .name           = "/proc/net/fib_trie",
        .comm           = "dnsmasq",
        .apparmor       = "AUDIT",
        .severity       = "audit",
        .requested_mask = "r",
        .denied_mask    = "",
        .fsuid          = 33,
        .ouid           = 0,
    },
    /* 2 */ {
        .profile        = "/usr/bin/parodus",
        .operation      = "exec",
        .name           = "/usr/bin/curl",
        .comm           = "parodus",
        .apparmor       = "DENIED",
        .severity       = "denied",
        .requested_mask = "x",
        .denied_mask    = "x",
        .fsuid          = 0,
        .ouid           = 0,
    },
    /* 3 */ {
        .profile        = "/usr/bin/parodus",
        .operation      = "open",
        .name           = "/etc/ssl/private/key.pem",
        .comm           = "parodus",
        .apparmor       = "DENIED",
        .severity       = "denied",
        .requested_mask = "r",
        .denied_mask    = "r",
        .fsuid          = 0,
        .ouid           = 0,
    },
    /* 4 */ {
        .profile        = "/usr/sbin/dnsmasq",
        .operation      = "connect",
        .name           = "socket:[family=2,type=1]",
        .comm           = "dnsmasq",
        .apparmor       = "DENIED",
        .severity       = "denied",
        .requested_mask = "w",
        .denied_mask    = "w",
        .fsuid          = 33,
        .ouid           = 33,
    },
    /* 5 */ {
        .profile        = "/usr/bin/rbus_elements",
        .operation      = "open",
        .name           = "/proc/sys/kernel/hostname",
        .comm           = "rbus_elements",
        .apparmor       = "AUDIT",
        .severity       = "audit",
        .requested_mask = "r",
        .denied_mask    = "",
        .fsuid          = 0,
        .ouid           = 0,
    },
    /* 6 */ {
        .profile        = "/usr/sbin/dnsmasq",
        .operation      = "open",
        .name           = "/var/run/dnsmasq.pid",
        .comm           = "dnsmasq",
        .apparmor       = "ALLOWED",
        .severity       = "allowed",
        .requested_mask = "rw",
        .denied_mask    = "",
        .fsuid          = 33,
        .ouid           = 33,
    },
    /* 7 */ {
        .profile        = "/usr/bin/parodus",
        .operation      = "open",
        .name           = "/tmp/parodus_cfg.json",
        .comm           = "parodus",
        .apparmor       = "AUDIT",
        .severity       = "audit",
        .requested_mask = "rw",
        .denied_mask    = "",
        .fsuid          = 0,
        .ouid           = 0,
    },
    /* 8 */ {
        .profile        = "/usr/sbin/telemetry2_0",
        .operation      = "open",
        .name           = "/etc/telemetry/profile.json",
        .comm           = "telemetry2_0",
        .apparmor       = "DENIED",
        .severity       = "denied",
        .requested_mask = "r",
        .denied_mask    = "r",
        .fsuid          = 0,
        .ouid           = 0,
    },
    /* 9 */ {
        .profile        = "/usr/sbin/telemetry2_0",
        .operation      = "exec",
        .name           = "/usr/bin/curl",
        .comm           = "telemetry2_0",
        .apparmor       = "DENIED",
        .severity       = "denied",
        .requested_mask = "x",
        .denied_mask    = "x",
        .fsuid          = 0,
        .ouid           = 0,
    },
    /* 10 */ {
        .profile        = "/usr/bin/rbus_elements",
        .operation      = "open",
        .name           = "/sys/firmware/devicetree/base/serial-number",
        .comm           = "rbus_elements",
        .apparmor       = "AUDIT",
        .severity       = "audit",
        .requested_mask = "r",
        .denied_mask    = "",
        .fsuid          = 0,
        .ouid           = 0,
    },
    /* 11 */ {
        .profile        = "/usr/bin/parodus",
        .operation      = "open",
        .name           = "/etc/ssl/certs/ca-certificates.crt",
        .comm           = "parodus",
        .apparmor       = "ALLOWED",
        .severity       = "allowed",
        .requested_mask = "r",
        .denied_mask    = "",
        .fsuid          = 0,
        .ouid           = 0,
    },
};
